const KEY='markHanLivingThesis2026V2';
const clone=x=>JSON.parse(JSON.stringify(x));
function mergeDefaults(base,saved){if(Array.isArray(base))return Array.isArray(saved)?saved:clone(base);if(base&&typeof base==='object'){const out={};for(const k of Object.keys(base))out[k]=mergeDefaults(base[k],saved?.[k]);if(saved&&typeof saved==='object')for(const k of Object.keys(saved))if(!(k in out))out[k]=saved[k];return out}return saved===undefined?base:saved}
let DATA=(()=>{try{return mergeDefaults(window.DEFAULT_DATA,JSON.parse(localStorage.getItem(KEY)||'null'))}catch{return clone(window.DEFAULT_DATA)}})();
function normalizeDate(v=''){const m=String(v).trim().match(/^(\d{4})[.\/-](\d{1,2})[.\/-](\d{1,2})$/);return m?`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`:String(v).slice(0,10)}
function todayLocal(){const d=new Date(),z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}`}
for(const collection of ['notes','essays'])for(const item of DATA[collection]||[])item[1]=normalizeDate(item[1]);
let panel='site-brand';let dirty=false;let autosaveTimer=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function markDirty(){dirty=true;const el=$('#saveState');if(el){el.textContent='저장되지 않은 변경';el.classList.add('dirty')}clearTimeout(autosaveTimer);autosaveTimer=setTimeout(()=>save(false),1800)}
function save(showToast=true){syncEditors();try{localStorage.setItem(KEY,JSON.stringify(DATA));dirty=false;const el=$('#saveState');if(el){el.textContent='자동 저장됨';el.classList.remove('dirty')}if(showToast)toast('저장했습니다')}catch(e){toast('저장 공간이 부족합니다. 큰 이미지를 줄여주세요.')}}
function toast(x){const t=$('#toast');t.textContent=x;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;')}
function arr(v){return Array.isArray(v)?v.join(', '):v||''}
function plainToHTML(v=''){const s=String(v);if(/<\/?[a-z][\s\S]*>/i.test(s))return s;return s.split(/\n{2,}/).map(p=>`<p>${esc(p).replaceAll('\n','<br>')}</p>`).join('')}
function field(label,path,value,type='input',full=false){const control=type==='textarea'?`<textarea data-path="${path}">${esc(value)}</textarea>`:`<input type="${type==='date'?'date':'text'}" data-path="${path}" value="${esc(type==='date'?normalizeDate(value):value)}">`;return `<div class="field ${full?'full':''}"><label>${label}</label>${control}</div>`} 
function tagField(label,path,values=[]){const tags=Array.isArray(values)?values:arr(values).split(',').map(x=>x.trim()).filter(Boolean);return `<div class="field full tag-field"><label>${label}</label><div class="tag-editor" data-tag-path="${path}"><div class="tag-list">${tags.map((tag,i)=>`<span class="tag-chip"><input value="${esc(tag)}" aria-label="${esc(label)} ${i+1}" oninput="editTag('${path}',${i},this.value)"><button type="button" onclick="removeTag('${path}',${i})" aria-label="태그 삭제">×</button></span>`).join('')}</div><div class="tag-add"><input placeholder="새 태그 입력" onkeydown="tagKey(event,'${path}')"><button type="button" class="btn secondary" onclick="addTagFromButton(this,'${path}')">＋ 태그 추가</button></div><small>Enter를 누르거나 버튼을 눌러 원하는 만큼 추가할 수 있습니다.</small></div></div>`}
function getByPath(path){return path.split('.').reduce((o,k)=>o?.[k],DATA)}
function editTag(path,index,value){const a=getByPath(path);if(Array.isArray(a)){a[index]=value;markDirty()}}
function removeTag(path,index){syncEditors();const a=getByPath(path);if(Array.isArray(a)){a.splice(index,1);markDirty();render()}}
function addTag(path,value){const v=String(value||'').trim();if(!v)return;let a=getByPath(path);if(!Array.isArray(a)){setByPath(path,[]);a=getByPath(path)}if(!a.includes(v))a.push(v);markDirty();render()}
function tagKey(e,path){if(e.key==='Enter'||e.key===','){e.preventDefault();addTag(path,e.currentTarget.value)}}
function addTagFromButton(button,path){addTag(path,button.previousElementSibling.value)}
function toolbar(id){return `<div class="rich-toolbar" data-for="${id}">
<div class="tool-group"><select onchange="formatSelect(this,'formatBlock')" title="문단 형식"><option value="p">본문</option><option value="h2">제목 2</option><option value="h3">제목 3</option><option value="blockquote">인용</option></select><select onchange="formatSelect(this,'fontName')" title="폰트"><option value="Georgia">Serif</option><option value="Arial">Sans</option><option value="Noto Sans KR">Noto Sans</option><option value="Courier New">Mono</option></select><select onchange="formatSelect(this,'fontSize')" title="글자 크기"><option value="3">보통</option><option value="2">작게</option><option value="4">크게</option><option value="5">더 크게</option><option value="6">매우 크게</option></select></div>
<div class="tool-group"><button class="tool" onclick="cmd(event,'bold')"><b>B</b></button><button class="tool" onclick="cmd(event,'italic')"><i>I</i></button><button class="tool" onclick="cmd(event,'underline')"><u>U</u></button><button class="tool" onclick="cmd(event,'strikeThrough')"><s>S</s></button></div>
<div class="tool-group"><button class="tool" onclick="cmd(event,'justifyLeft')">≡</button><button class="tool" onclick="cmd(event,'justifyCenter')">≣</button><button class="tool" onclick="cmd(event,'justifyRight')">☰</button></div>
<div class="tool-group"><button class="tool" onclick="cmd(event,'insertUnorderedList')">• List</button><button class="tool" onclick="cmd(event,'insertOrderedList')">1. List</button></div>
<div class="tool-group"><button class="tool" onclick="makeLink(event)">Link</button><button class="tool" onclick="insertImageURL(event)">Image URL</button><label class="tool" title="이미지 업로드">Upload<input hidden type="file" accept="image/*" onchange="uploadImage(event)"></label></div>
<div class="tool-group"><button class="tool" onclick="cmd(event,'undo')">↶</button><button class="tool" onclick="cmd(event,'redo')">↷</button><button class="tool" onclick="cmd(event,'removeFormat')">Clear</button><button class="tool" onclick="toggleHTML(event)">&lt;/&gt;</button></div>
</div>`}
function richField(label,path,value){const id='ed-'+path.replaceAll('.','-');return `<div class="field full rich-field"><label>${label}</label><div class="rich-wrap">${toolbar(id)}<div id="${id}" class="rich-editor" contenteditable="true" data-path="${path}" data-placeholder="여기에 본문을 작성하세요…">${plainToHTML(value)}</div><textarea class="html-mode hidden" data-html-for="${id}"></textarea><div class="editor-foot"><span>텍스트를 선택한 뒤 서식을 적용하세요.</span><span class="word-count">0자</span></div></div></div>`}
function bind(){
  $$('[data-path]:not(.rich-editor)').forEach(e=>e.oninput=()=>{setByPath(e.dataset.path,e.value);markDirty()});
  $$('.rich-editor').forEach(e=>{e.oninput=()=>{setByPath(e.dataset.path,e.innerHTML);updateCount(e);markDirty()};e.onfocus=()=>window.activeEditor=e;updateCount(e)});
}
function updateCount(e){const c=e.closest('.rich-wrap').querySelector('.word-count');if(c)c.textContent=`${e.innerText.trim().length.toLocaleString()}자`}
function syncEditors(){$$('.rich-editor').forEach(e=>setByPath(e.dataset.path,e.innerHTML));$$('.html-mode:not(.hidden)').forEach(t=>{const ed=document.getElementById(t.dataset.htmlFor);if(ed){ed.innerHTML=t.value;setByPath(ed.dataset.path,ed.innerHTML)}})}
function setByPath(path,val){const a=path.split('.');let o=DATA;a.slice(0,-1).forEach(k=>o=o[k]);const last=a.at(-1);if(path.match(/(notes|essays)\.\d+\.1$/))o[last]=normalizeDate(val);else if(path.match(/research\.\d+\.2$/))o[last]=Number(val)||0;else o[last]=val}
function itemHead(x,type,i){return `<div class="item-head"><div class="item-title"><span class="item-id">${esc(x[0])}</span><b>${esc(x[3]||x[2]||'Untitled')}</b></div><button class="delete" onclick="remove('${type}',${i})">삭제</button></div>`}
function noteEditor(x,i,type){const essay=type==='essays';const frameworkIndex=essay?6:5,projectIndex=essay?7:6,researchIndex=essay?8:7;return `<div class="item">${itemHead(x,type,i)}<div class="grid">${field('날짜',`${type}.${i}.1`,x[1],'date')}${field('분류',`${type}.${i}.2`,x[2])}${field('제목',`${type}.${i}.3`,x[3],'textarea',true)}${field('요약',`${type}.${i}.4`,x[4],'textarea',true)}${essay?richField('본문',`${type}.${i}.5`,x[5]):''}${tagField('Ideas · Tags',`${type}.${i}.${frameworkIndex}`,x[frameworkIndex])}${tagField('Work · Tags',`${type}.${i}.${projectIndex}`,x[projectIndex])}${tagField('Research · Tags',`${type}.${i}.${researchIndex}`,x[researchIndex])}</div></div>`}
function conceptEditor(x,i){return `<div class="item">${itemHead(x,'concepts',i)}<div class="grid">${field('단계',`concepts.${i}.1`,x[1])}${field('개념',`concepts.${i}.2`,x[2])}${richField('설명',`concepts.${i}.3`,x[3])}</div></div>`}
function projectEditor(x,i){return `<div class="item">${itemHead(x,'projects',i)}<div class="grid">${field('상태',`projects.${i}.1`,x[1])}${field('분류',`projects.${i}.2`,x[2])}${field('제목',`projects.${i}.3`,x[3],'textarea',true)}${field('요약',`projects.${i}.4`,x[4],'textarea',true)}${richField('Problem',`projects.${i}.5`,x[5])}${richField('Approach',`projects.${i}.6`,x[6])}${richField('Next',`projects.${i}.7`,x[7])}</div></div>`}
function researchEditor(x,i){return `<div class="item">${itemHead(x,'research',i)}<div class="grid">${field('단계',`research.${i}.1`,x[1])}${field('진행률',`research.${i}.2`,x[2])}${field('질문',`research.${i}.3`,x[3],'textarea',true)}${richField('Hypothesis',`research.${i}.4`,x[4])}${richField('Method',`research.${i}.5`,x[5])}</div></div>`}
function section(title,body,description=''){return `<div class="item settings-section"><div class="item-head"><div class="item-title"><b>${title}</b></div></div>${description?`<p class="settings-help">${description}</p>`:''}<div class="grid">${body}</div></div>`}
function rowActions(type,addLabel='＋ 항목 추가'){return `<div class="field full row-actions"><button class="btn secondary" onclick="addSiteRow('${type}')">${addLabel}</button> <button class="btn secondary" onclick="removeSiteRow('${type}')">마지막 항목 삭제</button></div>`}
function siteBrandEditor(){const s=DATA.site;return [
section('브랜드 정체성',field('표시 이름','site.brand.name',s.brand.name)+field('주제·브랜드','site.brand.subject',s.brand.subject),'헤더와 푸터에 표시되는 최상위 정체성입니다.'),
section('내비게이션',Object.entries(s.nav).map(([k,v])=>field(k,`site.nav.${k}`,v)).join(''),'메뉴 이름과 기능 문구입니다. 짧은 일반 텍스트로 유지하세요.'),
section('검색·공유 메타데이터',field('브라우저 제목','site.meta.title',s.meta.title,'textarea',true)+field('검색·공유 설명','site.meta.description',s.meta.description,'textarea',true)+field('문서 언어','site.meta.language',s.meta.language),'화면보다 상위의 기술 정보이므로 서식은 적용되지 않습니다.')
].join('')}
function siteHomeEditor(){const s=DATA.site,h=s.home;return [
section('Home · Hero',field('상단 라벨','site.home.overline',h.overline)+richField('메인 제목','site.home.title',h.title)+richField('핵심 명제','site.home.thesis',h.thesis)+richField('소개문','site.home.intro',h.intro)+field('주 버튼','site.home.primaryButton',h.primaryButton)+field('보조 버튼','site.home.secondaryButton',h.secondaryButton),'홈의 최상위 메시지입니다.'),
section('Home · Current Thesis',field('라벨','site.home.currentLabel',h.currentLabel)+richField('제목','site.home.currentTitle',h.currentTitle)+richField('설명','site.home.currentText',h.currentText)),
section('Home · Writing',field('대표 글 라벨','site.home.featuredLabel',h.featuredLabel)+field('최근 글 라벨','site.home.latestLabel',h.latestLabel)+field('전체 글 보기','site.home.allWriting',h.allWriting)),
section('Home · Central Question',field('라벨','site.home.centralLabel',h.centralLabel)+richField('질문','site.home.centralQuestion',h.centralQuestion)+richField('설명','site.home.centralText',h.centralText)),
section('Home · Ideas & Field Notes',field('Ideas 라벨','site.home.themesLabel',h.themesLabel)+field('Field Notes 라벨','site.home.notesLabel',h.notesLabel)+richField('Field Notes 제목','site.home.notesTitle',h.notesTitle)+richField('Field Notes 설명','site.home.notesText',h.notesText)),
section('Home · Timeline',field('라벨','site.home.timelineLabel',h.timelineLabel)+s.timeline.map((x,i)=>`<div class="field"><label>연도 ${i+1}</label><input data-path="site.timeline.${i}.0" value="${esc(x[0])}"></div><div class="field"><label>설명 ${i+1}</label><input data-path="site.timeline.${i}.1" value="${esc(x[1])}"></div>`).join('')+rowActions('timeline','＋ 타임라인 추가')+richField('마무리 문장','site.home.closing',h.closing))
].join('')}
function pageSection(key,p){let extra='';if(key==='journal')extra=field('검색 placeholder',`site.pages.${key}.search`,p.search)+field('전체 필터',`site.pages.${key}.all`,p.all)+field('에세이 필터',`site.pages.${key}.essays`,p.essays)+field('노트 필터',`site.pages.${key}.notes`,p.notes);return section(`Section · ${key}`,field('상단 라벨',`site.pages.${key}.overline`,p.overline)+richField('페이지 제목',`site.pages.${key}.title`,p.title)+richField('페이지 설명',`site.pages.${key}.description`,p.description)+extra)}
function sitePagesEditor(){return Object.entries(DATA.site.pages).filter(([key])=>key!=='about').map(([key,p])=>pageSection(key,p)).join('')}
function siteAboutEditor(){const s=DATA.site;return [
pageSection('about',s.pages.about),
section('About · Story',s.about.paragraphs.map((v,i)=>richField(`문단 ${i+1}`,`site.about.paragraphs.${i}`,v)).join('')+rowActions('paragraphs','＋ 문단 추가'),'경력 목록보다 문제의식과 서사를 설명하는 본문입니다.'),
section('About · Facts',s.about.facts.map((x,i)=>`<div class="field"><label>라벨 ${i+1}</label><input data-path="site.about.facts.${i}.0" value="${esc(x[0])}"></div>${richField(`내용 ${i+1}`,`site.about.facts.${i}.1`,x[1])}`).join('')+rowActions('facts','＋ 정보 추가'))
].join('')}
function siteSystemEditor(){const s=DATA.site;return [
section('공통 UI 라벨',Object.entries(s.labels).map(([k,v])=>field(k,`site.labels.${k}`,v,'textarea',true)).join(''),'버튼, 상태명, 상세 화면 제목처럼 기능적 역할을 하는 문구입니다.'),
section('Footer',richField('첫 문장','site.footer.line1',s.footer.line1)+richField('두 번째 문장','site.footer.line2',s.footer.line2)+field('저작권','site.footer.copyright',s.footer.copyright)+field('편집 링크','site.footer.edit',s.footer.edit))
].join('')}
function siteEditor(){if(panel==='site-brand')return siteBrandEditor();if(panel==='site-home')return siteHomeEditor();if(panel==='site-pages')return sitePagesEditor();if(panel==='site-about')return siteAboutEditor();return siteSystemEditor()}
function addSiteRow(type){syncEditors();if(type==='timeline')DATA.site.timeline.push(['연도','설명']);if(type==='paragraphs')DATA.site.about.paragraphs.push('새 문단');if(type==='facts')DATA.site.about.facts.push(['LABEL','내용']);markDirty();render()}
function removeSiteRow(type){syncEditors();const a=type==='timeline'?DATA.site.timeline:type==='paragraphs'?DATA.site.about.paragraphs:DATA.site.about.facts;if(a.length&&confirm('마지막 항목을 삭제할까요?')){a.pop();markDirty();render()}}
function render(){syncEditors();$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===panel));const titles={'site-brand':'Brand & Navigation','site-home':'Home','site-pages':'Section Pages','site-about':'About','site-system':'Footer & UI',notes:'Writing · Field Notes',essays:'Writing · Essays',concepts:'Ideas',projects:'Work',research:'Research'};$('#title').textContent=titles[panel];$('#addButton').style.display=panel.startsWith('site-')?'none':'';const c=$('#content');if(panel.startsWith('site-'))c.innerHTML=siteEditor();if(panel==='notes')c.innerHTML=DATA.notes.map((x,i)=>noteEditor(x,i,'notes')).join('');if(panel==='essays')c.innerHTML=DATA.essays.map((x,i)=>noteEditor(x,i,'essays')).join('');if(panel==='concepts')c.innerHTML=DATA.concepts.map(conceptEditor).join('');if(panel==='projects')c.innerHTML=DATA.projects.map(projectEditor).join('');if(panel==='research')c.innerHTML=DATA.research.map(researchEditor).join('');bind()}
function targetEditor(source){const bar=source.closest('.rich-toolbar');return bar?document.getElementById(bar.dataset.for):window.activeEditor}
function focusEditor(source){const ed=targetEditor(source);if(ed)ed.focus();return ed}
function cmd(e,name,value=null){e.preventDefault();focusEditor(e.currentTarget);document.execCommand(name,false,value);document.execCommand('styleWithCSS',false,true);const ed=targetEditor(e.currentTarget);if(ed){ed.dispatchEvent(new Event('input'));}}
function formatSelect(sel,name){const ed=focusEditor(sel);document.execCommand(name,false,sel.value);if(ed)ed.dispatchEvent(new Event('input'));sel.blur()}
function makeLink(e){e.preventDefault();const ed=focusEditor(e.currentTarget);const url=prompt('링크 URL을 입력하세요','https://');if(!url)return;document.execCommand('createLink',false,url);if(ed)ed.dispatchEvent(new Event('input'))}
function insertImageURL(e){e.preventDefault();const ed=focusEditor(e.currentTarget);const url=prompt('이미지 URL을 입력하세요','https://');if(!url)return;document.execCommand('insertImage',false,url);if(ed)ed.dispatchEvent(new Event('input'))}
function uploadImage(e){const file=e.target.files[0];if(!file)return;const ed=targetEditor(e.currentTarget);if(file.size>1500000&&!confirm('이미지가 큽니다. 브라우저 저장 용량을 많이 사용할 수 있습니다. 계속할까요?')){e.target.value='';return}const r=new FileReader();r.onload=()=>{ed.focus();document.execCommand('insertImage',false,r.result);ed.dispatchEvent(new Event('input'));toast('이미지를 본문에 삽입했습니다')};r.readAsDataURL(file);e.target.value=''}
function toggleHTML(e){e.preventDefault();const ed=targetEditor(e.currentTarget),ta=ed.parentElement.querySelector(`[data-html-for="${ed.id}"]`);if(ta.classList.contains('hidden')){ta.value=ed.innerHTML;ed.classList.add('hidden');ta.classList.remove('hidden');ta.focus()}else{ed.innerHTML=ta.value;ta.classList.add('hidden');ed.classList.remove('hidden');ed.dispatchEvent(new Event('input'));ed.focus()}}
function add(){if(panel.startsWith('site-'))return;syncEditors();const id=Date.now();if(panel==='notes')DATA.notes.unshift(['n'+id,todayLocal(),'Field Note','새 노트','요약',['AI Native Healthcare'],['AI Native EMR'],['Can EMR become a decision system?']]);if(panel==='essays')DATA.essays.unshift(['e'+id,todayLocal(),'Essay','새 에세이','요약','<p>본문을 작성하세요.</p>',['AI Native Healthcare'],['AI Native EMR'],['Can EMR become a decision system?']]);if(panel==='concepts')DATA.concepts.push([String(DATA.concepts.length+1).padStart(2,'0'),'Exploring','새 개념','<p>설명을 작성하세요.</p>']);if(panel==='projects')DATA.projects.push(['p'+id,'Draft','Project','새 프로젝트','요약','<p>문제</p>','<p>접근</p>','<p>다음 단계</p>']);if(panel==='research')DATA.research.push(['r'+id,'Formulating',10,'새 연구 질문','<p>가설</p>','<p>방법</p>']);markDirty();render();window.scrollTo({top:0,behavior:'smooth'})}
function remove(type,i){if(confirm('삭제할까요?')){DATA[type].splice(i,1);markDirty();render()}}
function resetAll(){if(confirm('기본 콘텐츠로 되돌릴까요?')){DATA=clone(window.DEFAULT_DATA);save(true);render()}}
function exportJSON(){syncEditors();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(DATA,null,2)],{type:'application/json'}));a.download='mark-han-content.json';a.click();URL.revokeObjectURL(a.href)}
function importJSON(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{DATA=JSON.parse(r.result);save(true);render()}catch{toast('올바른 JSON 파일이 아닙니다')}};r.readAsText(f)}
document.addEventListener('DOMContentLoaded',()=>{$$('.nav button').forEach(b=>b.onclick=()=>{panel=b.dataset.panel;render()});render()});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});

/* Publishing workflow upgrade */
function slugify(v=''){return String(v).toLowerCase().trim().replace(/<[^>]*>/g,'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9가-힣]+/g,'-').replace(/^-+|-+$/g,'').slice(0,90)||'untitled'}
function metaIndex(type){return type==='essays'?9:8}
function ensurePublishingMeta(){
  for(const type of ['notes','essays']) for(const item of DATA[type]||[]){
    const idx=metaIndex(type); const old=item[idx];
    if(!old||typeof old!=='object'||Array.isArray(old)) item[idx]={status:'published',slug:slugify(item[3]),publishedAt:normalizeDate(item[1]),updatedAt:normalizeDate(item[1]),seoTitle:'',seoDescription:item[4]||'',coverImage:'',canonical:''};
    else item[idx]={status:'draft',slug:slugify(item[3]),publishedAt:'',updatedAt:todayLocal(),seoTitle:'',seoDescription:'',coverImage:'',canonical:'',...old};
  }
}
ensurePublishingMeta();
function selectField(label,path,value,options,full=false){return `<div class="field ${full?'full':''}"><label>${label}</label><select data-path="${path}">${options.map(o=>`<option value="${esc(o[0])}" ${o[0]===value?'selected':''}>${esc(o[1])}</option>`).join('')}</select></div>`}
function publicationFields(x,i,type){const idx=metaIndex(type),m=x[idx];return `<div class="publication-box"><div class="publication-head"><div><b>Publication</b><span class="status-badge status-${esc(m.status)}">${esc(m.status)}</span></div><div class="publication-actions"><button class="btn secondary" type="button" onclick="previewItem('${type}',${i})">Preview ↗</button><button class="btn secondary" type="button" onclick="setPublishStatus('${type}',${i},'draft')">Draft</button><button class="btn" type="button" onclick="setPublishStatus('${type}',${i},'published')">Publish</button><button class="btn secondary" type="button" onclick="setPublishStatus('${type}',${i},'archived')">Archive</button></div></div><div class="grid">${selectField('상태',`${type}.${i}.${idx}.status`,m.status,[['draft','Draft'],['review','Review'],['published','Published'],['archived','Archived']])}${field('URL slug',`${type}.${i}.${idx}.slug`,m.slug)}${field('발행일',`${type}.${i}.${idx}.publishedAt`,m.publishedAt,'date')}${field('수정일',`${type}.${i}.${idx}.updatedAt`,m.updatedAt,'date')}${field('SEO 제목',`${type}.${i}.${idx}.seoTitle`,m.seoTitle,'textarea',true)}${field('SEO 설명',`${type}.${i}.${idx}.seoDescription`,m.seoDescription,'textarea',true)}${field('커버 이미지 URL',`${type}.${i}.${idx}.coverImage`,m.coverImage,'textarea',true)}${field('Canonical URL',`${type}.${i}.${idx}.canonical`,m.canonical,'textarea',true)}</div></div>`}
function noteEditor(x,i,type){const essay=type==='essays';const frameworkIndex=essay?6:5,projectIndex=essay?7:6,researchIndex=essay?8:7;return `<div class="item">${itemHead(x,type,i)}${publicationFields(x,i,type)}<div class="grid">${field('날짜',`${type}.${i}.1`,x[1],'date')}${field('분류',`${type}.${i}.2`,x[2])}${field('제목',`${type}.${i}.3`,x[3],'textarea',true)}${field('요약',`${type}.${i}.4`,x[4],'textarea',true)}${essay?richField('본문',`${type}.${i}.5`,x[5]):''}${tagField('Ideas · Tags',`${type}.${i}.${frameworkIndex}`,x[frameworkIndex])}${tagField('Work · Tags',`${type}.${i}.${projectIndex}`,x[projectIndex])}${tagField('Research · Tags',`${type}.${i}.${researchIndex}`,x[researchIndex])}</div></div>`}
function setPublishStatus(type,i,status){syncEditors();ensurePublishingMeta();const m=DATA[type][i][metaIndex(type)];m.status=status;m.updatedAt=todayLocal();if(status==='published'&&!m.publishedAt)m.publishedAt=todayLocal();save(false);render();toast(status==='published'?'발행 상태로 변경했습니다. 발행 데이터 내보내기 후 서버에 업로드하세요.':`${status} 상태로 변경했습니다.`)}
function previewItem(type,i){syncEditors();save(false);const x=DATA[type][i];window.open(`index.html?preview=${encodeURIComponent(type+':'+x[0])}#journal`,'_blank')}
function publishingDashboard(){ensurePublishingMeta();const rows=[];for(const type of ['essays','notes'])DATA[type].forEach((x,i)=>rows.push({type,i,x,m:x[metaIndex(type)]}));rows.sort((a,b)=>(b.m.updatedAt||b.x[1]).localeCompare(a.m.updatedAt||a.x[1]));const counts={draft:0,review:0,published:0,archived:0};rows.forEach(r=>counts[r.m.status]=(counts[r.m.status]||0)+1);return `<div class="publish-summary">${Object.entries(counts).map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join('')}</div><div class="item"><div class="item-head"><div class="item-title"><b>Publication queue</b></div></div><div class="publish-table">${rows.map(r=>`<div class="publish-row"><div><span class="status-badge status-${esc(r.m.status)}">${esc(r.m.status)}</span><small>${r.type==='essays'?'Essay':'Field Note'} · ${esc(r.x[1])}</small></div><div><b>${esc(r.x[3])}</b><code>/${r.type==='essays'?'writing':'notes'}/${esc(r.m.slug)}</code></div><div><button class="btn secondary" onclick="previewItem('${r.type}',${r.i})">Preview</button><button class="btn" onclick="setPublishStatus('${r.type}',${r.i},'published')">Publish</button></div></div>`).join('')}</div></div><div class="item settings-section"><div class="item-head"><div class="item-title"><b>Static web publication</b></div></div><p class="settings-help">1. 글 상태를 Published로 변경합니다. 2. 상단의 ‘발행 데이터 내보내기’를 눌러 published-content.json을 생성합니다. 3. 기존 서버 파일의 같은 이름 파일을 교체하면 공개 사이트가 갱신됩니다.</p></div>`}
function render(){syncEditors();ensurePublishingMeta();$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.panel===panel));const titles={'site-brand':'Brand & Navigation','site-home':'Home','site-pages':'Section Pages','site-about':'About','site-system':'Footer & UI',publishing:'Publication Dashboard',notes:'Writing · Field Notes',essays:'Writing · Essays',concepts:'Ideas',projects:'Work',research:'Research'};$('#title').textContent=titles[panel];$('#addButton').style.display=(panel.startsWith('site-')||panel==='publishing')?'none':'';const c=$('#content');if(panel.startsWith('site-'))c.innerHTML=siteEditor();if(panel==='publishing')c.innerHTML=publishingDashboard();if(panel==='notes')c.innerHTML=DATA.notes.map((x,i)=>noteEditor(x,i,'notes')).join('');if(panel==='essays')c.innerHTML=DATA.essays.map((x,i)=>noteEditor(x,i,'essays')).join('');if(panel==='concepts')c.innerHTML=DATA.concepts.map(conceptEditor).join('');if(panel==='projects')c.innerHTML=DATA.projects.map(projectEditor).join('');if(panel==='research')c.innerHTML=DATA.research.map(researchEditor).join('');bind()}
function add(){if(panel.startsWith('site-')||panel==='publishing')return;syncEditors();const id=Date.now(),meta={status:'draft',slug:'untitled-'+id,publishedAt:'',updatedAt:todayLocal(),seoTitle:'',seoDescription:'',coverImage:'',canonical:''};if(panel==='notes')DATA.notes.unshift(['n'+id,todayLocal(),'Field Note','새 노트','요약',['AI Native Healthcare'],['AI Native EMR'],['Can EMR become a decision system?'],meta]);if(panel==='essays')DATA.essays.unshift(['e'+id,todayLocal(),'Essay','새 에세이','요약','<p>본문을 작성하세요.</p>',['AI Native Healthcare'],['AI Native EMR'],['Can EMR become a decision system?'],meta]);if(panel==='concepts')DATA.concepts.push([String(DATA.concepts.length+1).padStart(2,'0'),'Exploring','새 개념','<p>설명을 작성하세요.</p>']);if(panel==='projects')DATA.projects.push(['p'+id,'Draft','Project','새 프로젝트','요약','<p>문제</p>','<p>접근</p>','<p>다음 단계</p>']);if(panel==='research')DATA.research.push(['r'+id,'Formulating',10,'새 연구 질문','<p>가설</p>','<p>방법</p>']);markDirty();render();window.scrollTo({top:0,behavior:'smooth'})}
function publishedSnapshot(){syncEditors();ensurePublishingMeta();const out=clone(DATA);out.notes=out.notes.filter(x=>x[8]?.status==='published');out.essays=out.essays.filter(x=>x[9]?.status==='published');out.generatedAt=new Date().toISOString();return out}
function exportPublished(){const out=publishedSnapshot();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));a.download='published-content.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Published 콘텐츠만 내보냈습니다.')}
