const STORAGE_KEY='markHanLivingThesis2026V2';
const clone=x=>JSON.parse(JSON.stringify(x));
function mergeDefaults(base,saved){if(Array.isArray(base))return Array.isArray(saved)?saved:clone(base);if(base&&typeof base==='object'){const out={};for(const k of Object.keys(base))out[k]=mergeDefaults(base[k],saved?.[k]);if(saved&&typeof saved==='object')for(const k of Object.keys(saved))if(!(k in out))out[k]=saved[k];return out}return saved===undefined?base:saved}
function loadData(){try{return mergeDefaults(window.DEFAULT_DATA,JSON.parse(localStorage.getItem(STORAGE_KEY)||'null'))}catch{return clone(window.DEFAULT_DATA)}}
let DATA=loadData();const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const PREVIEW=new URLSearchParams(location.search).get('preview');
function itemMeta(x,type){const idx=type==='essay'?9:8;return x[idx]&&typeof x[idx]==='object'?x[idx]:{status:'published',slug:'',seoTitle:'',seoDescription:'',coverImage:'',canonical:''}}
function visibleItem(x,type){return itemMeta(x,type).status==='published'||PREVIEW===((type==='essay'?'essays':'notes')+':'+x[0])}
async function hydratePublished(){if(localStorage.getItem(STORAGE_KEY))return;try{const r=await fetch('published-content.json',{cache:'no-store'});if(r.ok)DATA=mergeDefaults(window.DEFAULT_DATA,await r.json())}catch(e){}}
function rich(v=''){const s=String(v);return /<\/?[a-z][\s\S]*>/i.test(s)?s:s.split(/\n{2,}/).map(p=>`<p>${p.replaceAll('\n','<br>')}</p>`).join('')}
function text(v=''){const d=document.createElement('div');d.innerHTML=String(v);return d.textContent||d.innerText||''}
function setHTML(id,v){const e=$('#'+id);if(e)e.innerHTML=v??''}function setText(id,v){const e=$('#'+id);if(e)e.textContent=v??''}
function applySite(){const s=DATA.site;
document.documentElement.lang=s.meta.language||'ko';document.title=text(s.meta.title);document.querySelector('meta[name="description"]').content=text(s.meta.description);
setText('brandName',s.brand.name);setText('brandSubject',s.brand.subject);$$('[data-nav]').forEach(e=>e.textContent=s.nav[e.dataset.nav]);$$('[data-drawer-nav]').forEach(e=>e.textContent=s.nav[e.dataset.drawerNav]);setText('editLink',s.nav.edit);setText('menuLabel',s.nav.menu);setText('drawerClose',s.nav.close);setText('drawerEdit',s.nav.editContent);
setText('homeOverline',s.home.overline);setHTML('homeTitle',s.home.title);setHTML('homeThesis',rich(s.home.thesis));setHTML('homeIntro',rich(s.home.intro));setText('homePrimary',s.home.primaryButton);setText('homeSecondary',s.home.secondaryButton);setText('currentLabel',s.home.currentLabel);setHTML('currentTitle',s.home.currentTitle);setHTML('currentText',rich(s.home.currentText));setText('featuredLabel',s.home.featuredLabel);setText('latestLabel',s.home.latestLabel);setText('allWriting',s.home.allWriting);setText('centralLabel',s.home.centralLabel);setHTML('centralQuestion',rich(s.home.centralQuestion));setHTML('centralText',rich(s.home.centralText));setText('themesLabel',s.home.themesLabel);setText('notesLabel',s.home.notesLabel);setHTML('notesTitle',s.home.notesTitle);setHTML('notesText',rich(s.home.notesText));setText('timelineLabel',s.home.timelineLabel);setHTML('timelineClosing',s.home.closing);$('#timeline').innerHTML=s.timeline.map(x=>`<div><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');
for(const key of ['journal','framework','projects','research','about']){const p=s.pages[key];setText(key+'Overline',p.overline);setHTML(key+'Title',p.title);setHTML(key+'Description',rich(p.description))}
$('#search').placeholder=s.pages.journal.search;setText('filterAll',s.pages.journal.all);setText('filterEssays',s.pages.journal.essays);setText('filterNotes',s.pages.journal.notes);
$('#aboutStory').innerHTML=s.about.paragraphs.map((p,i)=>`<p${i===0?' class="large"':''}>${rich(p).replace(/^<p>|<\/p>$/g,'')}</p>`).join('');$('#aboutFacts').innerHTML=s.about.facts.map(x=>`<div><span>${x[0]}</span><div class="fact-rich">${rich(x[1])}</div></div>`).join('');
setText('footerName',s.brand.name);setText('footerSubject',s.brand.subject);setHTML('footerLine1',rich(s.footer.line1));setHTML('footerLine2',rich(s.footer.line2));setText('footerCopyright',s.footer.copyright);setText('footerEdit',s.footer.edit)
}
function go(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));closeDrawer();window.scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'',`#${id}`)}
function openDrawer(){$('#drawer').classList.add('open');document.body.classList.add('locked')}function closeDrawer(){$('#drawer').classList.remove('open');document.body.classList.remove('locked')}
function renderHome(){const l=DATA.site.labels,pubEssays=DATA.essays.filter(x=>visibleItem(x,'essay')),pubNotes=DATA.notes.filter(x=>visibleItem(x,'note')),e=pubEssays[0];$('#featuredEssay').innerHTML=e?`<article class="featured" onclick="openItem('essay','${e[0]}')"><div><div class="featured-meta">${e[2]} · ${e[1]}</div></div><div><h2>${e[3]}</h2><p>${e[4]}</p><span class="read-mark">${l.readEssay}</span></div></article>`:'';const mixed=[...pubEssays.slice(1,4).map(x=>[x,'essay']),...pubNotes.slice(0,3).map(x=>[x,'note'])].sort((a,b)=>b[0][1].localeCompare(a[0][1])).slice(0,5);$('#latestWriting').innerHTML=mixed.map(([x,t])=>`<article class="writing-row" onclick="openItem('${t}','${x[0]}')"><time>${x[1].replaceAll('.','–')}</time><h3>${x[3]}</h3><span>${t==='essay'?l.essay:l.note} →</span></article>`).join('');$('#themeIndex').innerHTML=DATA.concepts.slice(0,6).map(x=>`<div class="theme-row"><span>${x[0]}</span><b>${x[2]}</b><span>${x[1]}</span></div>`).join('');$('#fieldNotes').innerHTML=pubNotes.slice(0,6).map(x=>`<article class="note-cell" onclick="openItem('note','${x[0]}')"><time>${x[1]}</time><p>${x[3]}</p><span>${x[2]} →</span></article>`).join('')}
function drawJournal(mode='all',q=''){const l=DATA.site.labels;let items=[];if(mode!=='essay')DATA.notes.filter(x=>visibleItem(x,'note')).forEach(x=>items.push([x,'note']));if(mode!=='note')DATA.essays.filter(x=>visibleItem(x,'essay')).forEach(x=>items.push([x,'essay']));items.sort((a,b)=>b[0][1].localeCompare(a[0][1]));$('#journalGrid').innerHTML=items.filter(([x])=>text(x[3]+x[4]).toLowerCase().includes(q.toLowerCase())).map(([x,t])=>`<article class="archive-item" onclick="openItem('${t}','${x[0]}')"><div class="meta">${x[1]}<br>${x[2]}</div><div><h2>${x[3]}</h2><p>${x[4]}</p></div><div class="arrow">${l.read}</div></article>`).join('')}
function render(){applySite();renderHome();drawJournal();const l=DATA.site.labels;$('#frameworkList').innerHTML=DATA.concepts.map(x=>`<article class="idea-row"><div class="num">${x[0]}</div><div><h2>${x[2]}</h2><div class="rich-snippet">${rich(x[3])}</div></div><div class="stage">${x[1]}</div></article>`).join('');$('#projectList').innerHTML=DATA.projects.map(x=>`<article class="case"><div class="case-kicker"><span>${x[2]}</span><span>${x[1]}</span></div><div><h2>${x[3]}</h2><p class="case-summary">${x[4]}</p><div class="case-facts"><div><small>${l.problem}</small><div class="rich-snippet">${rich(x[5])}</div></div><div><small>${l.approach}</small><div class="rich-snippet">${rich(x[6])}</div></div><div><small>${l.next}</small><div class="rich-snippet">${rich(x[7])}</div></div></div></div></article>`).join('');$('#researchList').innerHTML=DATA.research.map(x=>`<article class="research-piece"><header><div><span class="state">${x[1]}</span><h2>${x[3]}</h2></div><span class="percent">${x[2]}%</span></header><div class="research-rich"><b>${l.hypothesis}</b>${rich(x[4])}</div><div class="research-rich"><b>${l.method}</b>${rich(x[5])}</div></article>`).join('')}
function relationHTML(c,p,r){return `<div class="connections"><b>${DATA.site.labels.connections}</b><div>${[...c,...p,...r].map(v=>`<span class="pill">${v}</span>`).join('')}</div></div>`}
function openItem(type,id){const x=(type==='note'?DATA.notes:DATA.essays).find(v=>v[0]===id);if(!x||!visibleItem(x,type))return;const essay=type==='essay';const body=essay?x[5]:`${x[4]}\n\n${DATA.site.labels.developingNote}`;const rel=essay?[x[6],x[7],x[8]]:[x[5],x[6],x[7]];const m=itemMeta(x,type);document.title=text(m.seoTitle||x[3])+' — '+text(DATA.site.brand.name);document.querySelector('meta[name="description"]').content=text(m.seoDescription||x[4]);document.querySelector('meta[property="og:title"]').content=text(m.seoTitle||x[3]);document.querySelector('meta[property="og:description"]').content=text(m.seoDescription||x[4]);document.querySelector('meta[property="og:image"]').content=m.coverImage||'';document.querySelector('link[rel="canonical"]').href=m.canonical||location.href.split('?')[0]+'?article='+encodeURIComponent(m.slug||x[0]);$('#modalContent').innerHTML=`<button class="reader-close" onclick="closeModal()">${DATA.site.labels.close}</button><div class="eyebrow">${x[2]} · ${x[1]}</div><h1>${x[3]}</h1><p class="dek">${x[4]}</p><div class="prose">${rich(body)}</div>${relationHTML(...rel)}`;$('#modal').classList.add('open');document.body.classList.add('locked')}
function closeModal(){$('#modal').classList.remove('open');document.body.classList.remove('locked');document.title=text(DATA.site.meta.title)}
let mode='all';async function setup(){await hydratePublished();$$('.filter').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));drawJournal(mode,$('#search').value)});$('#search').oninput=e=>drawJournal(mode,e.target.value);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeDrawer()}});window.addEventListener('scroll',()=>{const h=document.documentElement;$('#progress').style.width=`${(h.scrollTop/(h.scrollHeight-h.clientHeight))*100}%`});render();const start=location.hash.slice(1);go(['journal','framework','projects','research','about'].includes(start)?start:'home')}
document.addEventListener('DOMContentLoaded',setup);
